events {
    worker_connections 1024;
}

http {
    server {
        listen 82;
        server_name uv2.mx;

        location / {
            root /mnt/c/Users/Alejandra/17289/nginx/3sitios/sitio2;
            index index.html;
        }
    }
}
