events {
    worker_connections 1024;
}

http {
    server {
        listen 83;
        server_name uv3.mx;

        location / {
            root /mnt/c/Users/Alejandra/17289/nginx/3sitios/sitio3;
            index index.html;
        }
    }
}
